title: Thinreports
description: A PDF generation tools for Ruby

baseurl: ""
url: "https://www.thinreports.org"

google_analytics: G-TBQLFS86LE

remote-theme: pages-themes/primer

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji

markdown: CommonMarkGhPages
commonmark:
  options:
    - UNSAFE
  extensions:
    - autolink
    - strikethrough
    - table
