name: Synchronize index.md with README.md in thinreports/thinreports

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update
      run: node .github/workflows/update-index.js

    # - run: cat index.md

    - name: Deploy if changed
      run: |
        if ! git diff --exit-code --quiet index.md; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Sync index.md" index.md
          git push
        else
          echo "There are no changes."
        fi
